import LoadableComponent from './../Loadable/index';
import { FundProjectionScreenOutlined, HomeOutlined, UserOutlined, TagsOutlined, AppstoreOutlined, InfoCircleOutlined } from '@ant-design/icons';

export const userRouter: any = [
  {
    path: '/user',
    name: 'user',
    title: 'User',
    component: LoadableComponent(() => import('../../components/Layout/UserLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/user/login',
    name: 'login',
    title: 'LogIn',
    component: LoadableComponent(() => import('../../scenes/Login')),
    showInMenu: false,
  },
  {
    path: '/user/register',
    name: 'register',
    title: 'Register',
    component: LoadableComponent(() => import('../../scenes/Register')),
    showInMenu: false,
  },
];

export const appRouters: any = [
  {
    path: '/',
    exact: true,
    name: 'home',
    permission: '',
    title: 'Home',
    component: LoadableComponent(() => import('../../components/Layout/AppLayout')),
    isLayout: true,
    showInMenu: false,
  }, 
  {
    path: '/logout',
    permission: '',
    title: 'Logout',
    name: 'logout',
    showInMenu: false,
    component: LoadableComponent(() => import('../../components/Logout')),
  }, 
  {
    path: '/exception?:type',
    permission: '',
    title: 'exception',
    name: 'exception',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Exception')),
  }, 
  {
    path: '/account',
    permission: '',
    title: 'Account', 
    name: 'account',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Account')),
  },
  {
    path: '/dashboard',
    permission: '',
    title: 'Dashboard',
    name: 'dashboard',
    icon: HomeOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Dashboard')),
  }, 
  {
    path: '/tenants',
    permission: 'Pages.Tenants',
    title: 'Tenants',
    name: 'tenant',
    icon: AppstoreOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Tenants')),
  },
  {
    path: '/users',
    permission: 'Pages.Users',
    title: 'Users',
    name: 'user',
    icon: UserOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Users')),
  },
  {
    path: '/roles',
    permission: 'Pages.Roles',
    title: 'Roles',
    name: 'role',
    icon: TagsOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Roles')),
  },
  {
    path: '/about',
    permission: '',
    title: 'About',
    name: 'about',
    icon: InfoCircleOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/About')),
  }, 
  {
    path: '/projects',
    permission: '',
    title: 'Projects',
    name: 'projects',
    icon: FundProjectionScreenOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Projects')),
  },  
  {
    path: '/myprojects',
    permission: '',
    title: 'My projects',
    name: 'myprojects',
    icon: FundProjectionScreenOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/MyProjects')),
  }, 
  {
    path: '/myprojects/new',
    permission: '',
    title: 'New project',
    name: 'newproject', 
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/EditProject')),
  },
  {
    path: '/myprojects/edit/:id',
    permission: '',
    title: 'Edit project',
    name: 'editproject', 
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/EditProject')),
  }, 
  {
    path: '/project/:id',
    permission: '',
    title: 'Project info',
    name: 'project', 
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Project')),
  }, 
  {
    path: '/component/:id',
    permission: '',
    title: 'Component info',
    name: 'component', 
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Component')),
  },
  ///////////////////////// 
  /*{
    path: '/ticket/:id',
    permission: '',
    title: 'Ticket info',
    name: 'ticket', 
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Ticket')),
  },
  /*{
    path: '/tickets/edit/:id',
    permission: '',
    title: 'Edit ticket',
    name: 'editticket', 
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Component')),
  }, 
  {
    path: '/tickets/new?:componentId',
    permission: '',
    title: 'New ticket',
    name: 'newticket', 
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Component')),
  }, */ 
];

export const routers = [...userRouter, ...appRouters];
